namespace MoMoSdk.Enums;

public enum MoMoResultCode : ushort
{
    Successful = 0,
    TransactionIsAuthorizedSuccessfully = 9000,
    TransactionIsPreAuthorizedWaitingForUserConfirmation = 8000,
    TransactionIsBeingProcessed = 7000,
    TransactionIsBeingProcessedByTheProviderOfThePaymentInstrumentSelected = 7002,
    TransactionIsInitiatedWaitingForUserConfirmation = 1000,
    AccessDenied = 11,
    UnsupportedApiVersionForThisRequest = 12,
    MerchantAuthenticationFailed = 13,
    BadFormatRequest = 20,
    InvalidTransactionAmount = 22,
    DuplicatedRequestId = 40,
    DuplicatedOrderId = 41,
    InvalidOrderIdOrOrderIdIsNotFound = 42,
    RequestRejectedDueToAnAnalogousTransactionIsBeingProcessed = 43,
    TransactionRejectedDueToInvalidPaymentCode = 44,
    TransactionFailedDueToInsufficientFunds = 1001,
    TransactionRejectedByTheIssuersOfThePaymentMethods = 1002,
    TransactionCancelledAfterSuccessfullyAuthorized = 1003,
    TransactionFailedBecauseTheAmountExceedsDailyMonthlyPaymentLimit = 1004,
    TransactionFailedBecauseTheUrlOrQrCodeExpired = 1005,
    TransactionFailedBecauseUserHasDeniedToConfirmThePayment = 1006,
    TransactionRejectedDueToInactiveOrNonexistentUsersAccount = 1007,
    TransactionRestrictedDueToPromotionRules = 1026,
    TheOrderFailedDueToInvalidInformation = 1030,
    RefundRejectedTheOriginalTransactionCannotBeFound = 1080,
    RefundRejectedTheOriginalTransactionMightHaveBeenRefunded = 1081,
    TransactionFailedDueToInvalidToken = 2001,
    TransactionFailedDueToInactiveToken = 2007,
    BindingFailedBecauseUserHasDeniedToConfirmTheAuthorization = 3001,
    BindingRejectedDueToAuthorizationRestrictions = 3002,
    UnbindingRejectedDueToAuthorizationRestrictions = 3003,
    TokenCannotBeProvokedDueToPendingTransactions = 3004,
    TransactionRestrictedDueToIncompleteKYCs = 4001,
    OtpVerificationFailed = 4010,
    OtpIsNotSentOrTimeout = 4011,
    TransactionFailedBecauseUserHasFailedToLogin = 4100,
    VerificationFailed3ds = 4015,
    SystemIsUnderMaintenance = 10,
    UnknownError = 99,
}